import Head from 'next/head'
import Banner from '@/components/Banner'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner colour="blue" />
      <main className={styles.main}>
        Content Here
      </main>
    </>
  )
}
